### ISSUE TITLE
Initial TODO

### ISSUE THREAD

**Issue by JohnAD** [JohnAD/json-standard#1]
- [ ] Read file in, write file out; do so recursively in the data while NOT invoking code recursion (use static state array with depth 1000)
- [ ] enforce format (except sorting) while writing web site spec
- [ ] add DUCET collation library; sort object fields before (or while) serializing
- [ ] write unit tests and verify decimal float number reading/writing
- [ ] support -o option and write to new file
- [ ] unit tests, unit tests, unit tests
